//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//


package com.cvf.model.trainingdb;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.garmin.xmlschemas.trainingcenterdatabase.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Time_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "Time");
    private final static QName _Name_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "Name");
    private final static QName _DistanceMeters_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "DistanceMeters");
    private final static QName _Intensity_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "Intensity");
    private final static QName _LatitudeDegrees_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "LatitudeDegrees");
    private final static QName _VersionMinor_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "VersionMinor");
    private final static QName _Id_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "Id");
    private final static QName _VersionMajor_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "VersionMajor");
    private final static QName _UnitId_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "UnitId");
    private final static QName _Calories_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "Calories");
    private final static QName _Value_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "Value");
    private final static QName _TriggerMethod_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "TriggerMethod");
    private final static QName _LongitudeDegrees_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "LongitudeDegrees");
    private final static QName _LangID_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "LangID");
    private final static QName _BuildMajor_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "BuildMajor");
    private final static QName _BuildMinor_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "BuildMinor");
    private final static QName _MaximumSpeed_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "MaximumSpeed");
    private final static QName _PartNumber_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "PartNumber");
    private final static QName _ProductID_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "ProductID");
    private final static QName _AltitudeMeters_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "AltitudeMeters");
    private final static QName _TotalTimeSeconds_QNAME = new QName("http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", "TotalTimeSeconds");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.garmin.xmlschemas.trainingcenterdatabase.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link HeartRateBpm }
     * 
     */
    public HeartRateBpm createHeartRateBpm() {
        return new HeartRateBpm();
    }

    /**
     * Create an instance of {@link Trackpoint }
     * 
     */
    public Trackpoint createTrackpoint() {
        return new Trackpoint();
    }

    /**
     * Create an instance of {@link Lap }
     * 
     */
    public Lap createLap() {
        return new Lap();
    }

    /**
     * Create an instance of {@link MaximumHeartRateBpm }
     * 
     */
    public MaximumHeartRateBpm createMaximumHeartRateBpm() {
        return new MaximumHeartRateBpm();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link Activities }
     * 
     */
    public Activities createActivities() {
        return new Activities();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link Build }
     * 
     */
    public Build createBuild() {
        return new Build();
    }

    /**
     * Create an instance of {@link AverageHeartRateBpm }
     * 
     */
    public AverageHeartRateBpm createAverageHeartRateBpm() {
        return new AverageHeartRateBpm();
    }

    /**
     * Create an instance of {@link Creator }
     * 
     */
    public Creator createCreator() {
        return new Creator();
    }

    /**
     * Create an instance of {@link Track }
     * 
     */
    public Track createTrack() {
        return new Track();
    }

    /**
     * Create an instance of {@link TrainingCenterDatabase }
     * 
     */
    public TrainingCenterDatabase createTrainingCenterDatabase() {
        return new TrainingCenterDatabase();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "Time")
    public JAXBElement<XMLGregorianCalendar> createTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Time_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "DistanceMeters")
    public JAXBElement<String> createDistanceMeters(String value) {
        return new JAXBElement<String>(_DistanceMeters_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "Intensity")
    public JAXBElement<String> createIntensity(String value) {
        return new JAXBElement<String>(_Intensity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "LatitudeDegrees")
    public JAXBElement<BigDecimal> createLatitudeDegrees(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_LatitudeDegrees_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "VersionMinor")
    public JAXBElement<Byte> createVersionMinor(Byte value) {
        return new JAXBElement<Byte>(_VersionMinor_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "Id")
    public JAXBElement<XMLGregorianCalendar> createId(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Id_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "VersionMajor")
    public JAXBElement<Byte> createVersionMajor(Byte value) {
        return new JAXBElement<Byte>(_VersionMajor_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "UnitId")
    public JAXBElement<Long> createUnitId(Long value) {
        return new JAXBElement<Long>(_UnitId_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "Calories")
    public JAXBElement<Byte> createCalories(Byte value) {
        return new JAXBElement<Byte>(_Calories_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "Value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "TriggerMethod")
    public JAXBElement<String> createTriggerMethod(String value) {
        return new JAXBElement<String>(_TriggerMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "LongitudeDegrees")
    public JAXBElement<BigDecimal> createLongitudeDegrees(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_LongitudeDegrees_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "LangID")
    public JAXBElement<String> createLangID(String value) {
        return new JAXBElement<String>(_LangID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "BuildMajor")
    public JAXBElement<String> createBuildMajor(String value) {
        return new JAXBElement<String>(_BuildMajor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "BuildMinor")
    public JAXBElement<String> createBuildMinor(String value) {
        return new JAXBElement<String>(_BuildMinor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "MaximumSpeed")
    public JAXBElement<BigDecimal> createMaximumSpeed(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MaximumSpeed_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "PartNumber")
    public JAXBElement<String> createPartNumber(String value) {
        return new JAXBElement<String>(_PartNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "ProductID")
    public JAXBElement<String> createProductID(String value) {
        return new JAXBElement<String>(_ProductID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "AltitudeMeters")
    public JAXBElement<BigDecimal> createAltitudeMeters(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AltitudeMeters_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", name = "TotalTimeSeconds")
    public JAXBElement<BigDecimal> createTotalTimeSeconds(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TotalTimeSeconds_QNAME, BigDecimal.class, null, value);
    }

}
