//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//


package garmin.xmlschemas.trainingcenterdatabase.v2;

import java.math.BigDecimal;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Time"/>
 *         &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Position" minOccurs="0"/>
 *         &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}AltitudeMeters" minOccurs="0"/>
 *         &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}DistanceMeters" minOccurs="0"/>
 *         &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}HeartRateBpm" minOccurs="0"/>
 *         &lt;element ref="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "time",
    "position",
    "altitudeMeters",
    "distanceMeters",
    "heartRateBpm",
    "extensions"
})
@XmlRootElement(name = "Trackpoint")
public class Trackpoint {

    @XmlElement(name = "Time", required = true)
    protected XMLGregorianCalendar time;
    @XmlElement(name = "Position")
    protected Position position;
    @XmlElement(name = "AltitudeMeters")
    protected BigDecimal altitudeMeters;
    @XmlElement(name = "DistanceMeters")
    protected String distanceMeters;
    @XmlElement(name = "HeartRateBpm")
    protected HeartRateBpm heartRateBpm;
    @XmlElement(name = "Extensions")
    protected Extensions extensions;

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setPosition(Position value) {
        this.position = value;
    }

    /**
     * Gets the value of the altitudeMeters property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAltitudeMeters() {
        return altitudeMeters;
    }

    /**
     * Sets the value of the altitudeMeters property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAltitudeMeters(BigDecimal value) {
        this.altitudeMeters = value;
    }

    /**
     * Gets the value of the distanceMeters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistanceMeters() {
        return distanceMeters;
    }

    /**
     * Sets the value of the distanceMeters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistanceMeters(String value) {
    	if (value == null){
    	    value = "0.0";
    	}
    	nullOrAbsent("DistanceMeters", value);
    	
        this.distanceMeters = value;
    }

    private static void nullOrAbsent(String property, String value){
    	System.out.print(property);
    	if (null == value){
    		System.out.println(" Absent - ");
   
    	}else{
    		System.out.println(" value - ");
    	}
    	
    }
    /**
     * Gets the value of the heartRateBpm property.
     * 
     * @return
     *     possible object is
     *     {@link HeartRateBpm }
     *     
     */
    public HeartRateBpm getHeartRateBpm() {
    	
        return heartRateBpm;
    }

    /**
     * Sets the value of the heartRateBpm property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeartRateBpm }
     *     
     */
    public void setHeartRateBpm(HeartRateBpm value) {
    	
        this.heartRateBpm = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

}
