//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.09 at 12:20:23 PM MDT 
//


package garmin.xmlschemas.activityextension.v2;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.garmin.xmlschemas.activityextension.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AvgSpeed_QNAME = new QName("http://www.garmin.com/xmlschemas/ActivityExtension/v2", "AvgSpeed");
    private final static QName _Speed_QNAME = new QName("http://www.garmin.com/xmlschemas/ActivityExtension/v2", "Speed");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.garmin.xmlschemas.activityextension.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TPX }
     * 
     */
    public TPX createTPX() {
        return new TPX();
    }

    /**
     * Create an instance of {@link LX }
     * 
     */
    public LX createLX() {
        return new LX();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/ActivityExtension/v2", name = "AvgSpeed")
    public JAXBElement<BigDecimal> createAvgSpeed(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AvgSpeed_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.garmin.com/xmlschemas/ActivityExtension/v2", name = "Speed")
    public JAXBElement<String> createSpeed(String value) {
        return new JAXBElement<String>(_Speed_QNAME, String.class, null, value);
    }

}
