//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.22 at 04:31:13 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.garmin.com/xmlschemas/ActivityExtension/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package garmin.xmlschemas.activityextension.v2;
